DROP TABLE IF EXISTS tipp;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  token TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_admin INTEGER DEFAULT 0
);

CREATE TABLE tipp (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  compiled TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  template TEXT DEFAULT "default",
  FOREIGN KEY (user_id) REFERENCES user (id)
);
